#!/usr/bin/env bash
#
# pdd.sh - TPDD1 client in (almost) pure bash
# Brian K. White b.kenyon.w@gmail.com
# https://archive.org/details/TandyPortableDiskDriveSoftwareManual26-3808s/

# TODOS: Many ;)
# * ls after every command?
# * 2 or 3-column ls format? (so a full disk still fits on screen)
# * FDC commands
# * TPDD2
# * Refactor the global variable names to have a consistent scheme
# * Help screen
# * Shorter tty read timeout where possible
# * Give lcmd_save() an option to append just for completeness
# * Re-implement lcmd_mv based on fdc commands to edit the directory

###############################################################################
# config

# verbose/debug
# 0/unset=normal, 1=verbose, >1=more verbose, 3=log all tty traffic to files
# DEBUG=1 ./pdd ...
v=${DEBUG:-0}

# true/false - Automatically convert filenames to Floppy/Flopy2-compatible 6.2 .
# When saving, pad to %-6s.%-2s  : "A.BA"      -> "A     .BA"
# When loading, strip all spaces : "A     .BA" -> "A.BA"
# You need to do this to be compatible with Floppy, Flopy2, TS-DOS, etc.
# But the drive doesn't care, and Model T's are not the only TPDD users(1).
# So the automatic 6.2 padding can be disabled by setting this to false.
# This can be done at run-time from the commandline:
#     $> FLOPPY_COMPAT=false ./pdd save myfilename.exe
# Even when enabled, if a filename wouldn't fit within 6.2, then it is
# not modified, so enabled generally does the expected thing automatically.
# (1) TANDY WP-2, Brother knitting machines, Cambridge Z-88, MS-DOS & most OS's
: ${FLOPPY_COMPAT:=true}

# Default rs232 tty device name, with platform differences
# The automatic TPDD port detection will search "/dev/${TPDD_TTY_PREFIX}*"
			stty_f="-F" TPDD_TTY_PREFIX=ttyUSB		# linux
case "${OSTYPE,,}" in
	*bsd*) 		stty_f="-f" TPDD_TTY_PREFIX=ttyU ;;		# *bsd
	darwin*) 	stty_f="-f" TPDD_TTY_PREFIX=cu.usbserial- ;;	# osx
esac

# stty flags to set the serial port parameters & tty behavior
# For 9600-only drives like FB-100 or FDD19, change 19200 to 9600
# (FB-100/FDD19 can run at 19200 by removing the solder blob from dip switch 1)
# To disable RTS/CTS hardware flow control, change "crtscts" to "-crtscts"
STTY_FLAGS="19200 crtscts raw pass8 -echo clocal cread flusho -drain"

# This is silly but fun. Define your own animation frames for the spinner.
# As many frames as you want, frames can be as many bytes wide as you you want.
# All frames in a given set should be the same length. Use the "anim" or "play"
# command to test the animation without having to save and delete a file.
# Example: "anim 100" just plays the animation for 100 frames.
#SPINNER_ANIMATION_FRAMES=('-' '\' '|' '/')	# spinner
#SPINNER_ANIMATION_FRAMES=('       ' '   .   ' '   o   ' '  ( )  ' ' (   ) ' '(     )')	# warp
#SPINNER_ANIMATION_FRAMES=("... ..!" ".!...!!" ".'...!'" ". !..' " "!.!.! ." "'.!!'!." " .'!.'." ".. '. !" ) # fire, kinda
#SPINNER_ANIMATION_FRAMES=('[ ]' '[.]' '[o]' '[O]' "[']") # bloop
SPINNER_ANIMATION_FRAMES=('[o]' '[ ]')		# blinker
#SPINNER_ANIMATION_FRAMES=(
#	'stock ticker... '
#	'tock ticker... s'
#	'ock ticker... st'
#	'ck ticker... sto'
#	'k ticker... stoc'
#	' ticker... stock'
#	'ticker... stock '
#	'icker... stock t'
#	'cker... stock ti'
#	'ker... stock tic'
#	'er... stock tick'
#	'r... stock ticke'
#	'... stock ticker'
#	'.. stock ticker.'
#	'. stock ticker..'
#	' stock ticker...'
#)

###############################################################################

# tty read timeout in ms
# When issuing the "read" command to read bytes from the serial port, wait this
# long (in ms) for a byte to appear before giving up.
# Smaller numbers make some operations like "ls" go faster, but make other
# operations like "save" fail. 100 is marginal. 120 is safe.
TTY_READ_TIMEOUT_MS=120

# Default tpdd_wait() timout in ms
# Wait this long (by default) for the drive to respond after issuing a command.
# Some commands like dirent(get_first) and close can take 2 seconds to respond.
# Some commands like format take 100 seconds.
TPDD_WAIT_TIMEOUT_MS=5000

# How long to wait for format to complete
# Usually takes just under 100 seconds.
FORMAT_WAIT_MS=102000

# How long to wait for delete to complete
# Delete takes from 3 to 20 seconds. Larger files take longer.
# 65534 byte file takes 20.2 seconds, so 30 seconds should be safe.
DELETE_WAIT_MS=30000

# If you try to save a file with more than this many bytes, the drive will
# error with "Disk Full", even if the disk isn't full.
MAX_FILE_SIZE=65534

# end of config
###############################################################################

###############################################################################
# drive operating modes
typeset -ra mode=(
	[0]=fdc		# "FDC mode"
	[1]=opr		# "operation mode"
)

###############################################################################
# "Operation Mode" constants

# Operation Mode Request/Return Block Formats
typeset -rA opr_fmt=(
	# requests
	[req_dirent]='00'
	[req_open]='01'
	[req_close]='02'
	[req_read]='03'
	[req_write]='04'
	[req_delete]='05'
	[req_format]='06'
	[req_status]='07'
	[req_fdc]='08'
	# returns
	[ret_read]='10'
	[ret_dirent]='11'
	[ret_std]='12'	# error open close delete status write
)

# Operation Mode Error Codes
typeset -rA opr_msg=(
	[00]='Operation Complete'
	[10]='File Not Found'
	[30]='Command Parameter or Sequence Error'
	[40]='Read Error 0'
	[41]='Read Error 1'
	[42]='Read Error 2'
	[43]='Read Error 3'
	[44]='Read Error 4'
	[45]='Disk Not Formatted' # 'Read Error 5'
	[46]='Read Error 6'
	[47]='Read Error 7'
	[48]='Read Error 8'
	[49]='Read Error 9'
	[4A]='Read Error A'
	[4B]='Read Error B'
	[4C]='Read Error C'
	[4D]='Read Error D'
	[4E]='Read Error E'
	[4F]='Read Error F'
	[50]='Write-Protected Disk'
	[60]='Disk Full or Max File Size Exceeded' # 'Disk Full'
	[70]='Disk Insertion Error 0'
	[71]='Disk Not Inserted'      # 'Disk Insertion Error 1'
	[72]='Disk Insertion Error 2'
	[73]='Disk Insertion Error 3'
	[74]='Disk Insertion Error 4'
	[75]='Disk Insertion Error 5'
	[76]='Disk Insertion Error 6'
	[77]='Disk Insertion Error 7'
	[78]='Disk Insertion Error 8'
	[79]='Disk Insertion Error 9'
	[7A]='Disk Insertion Error A'
	[7B]='Disk Insertion Error B'
	[7C]='Disk Insertion Error C'
	[7D]='Disk Insertion Error D'
	[7E]='Disk Insertion Error E'
	[7F]='Disk Insertion Error F'
	[80]='Hardware Fault 0'
	[81]='Hardware Fault 1'
	[82]='Hardware Fault 2'
	[83]='Hardware Fault 3'
	[84]='Hardware Fault 4'
	[85]='Hardware Fault 5'
	[86]='Hardware Fault 6'
	[87]='Hardware Fault 7'
	[88]='Hardware Fault 8'
	[89]='Hardware Fault 9'
	[8A]='Hardware Fault A'
	[8B]='Hardware Fault B'
	[8C]='Hardware Fault C'
	[8D]='Hardware Fault D'
	[8E]='Hardware Fault E'
	[8F]='Hardware Fault F'
)

# Directory Entry Search Forms
typeset -rA dirent_cmd=(
	[set_name]=0
	[get_first]=1
	[get_next]=2
)

# File Open Access Modes
typeset -rA open_mode=(
	[write_new]=1
	[write_append]=2
	[read]=3
)

###############################################################################
# "FDC Mode" constants


# FDC Mode Commands
typeset -rA fdc_cmd=(
	[mode]='M'
	[condition]='D'
	[format]='F'
	[formatnv]='G'
	[readid]='A'
	[readsect]='R'
	[searchid]='S'
	[writeid]='B'
	[writeidnv]='C'
	[writesect]='W'
	[writesectnv]='X'
)

# FDC Mode Errors
typeset -rA fdc_msg=(
	[0]="OK"
	[193]="Command Error"
)

###############################################################################
# generic/util functions

abrt () {
	echo "$0: $@" >&2
	exit 1
}

vecho () {
	local -i l="$1" ;shift
	((v>=l)) && echo "$@" >&2
	:
}

_sleep () {
	local x
	read -t ${1:-1} -u 4 x
}

# Convert a plain text string to hex pairs stored in hex[]
str_to_hex () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local x="$*" ;local -i i l=${#x} ;hex=()
	for ((i=0;i<l;i++)) { printf -v hex[i] '%02x' "'${x:i:1}" ; }
	vecho 1 "$z: hex=(${hex[*]})"
}

# Read a local file into hex pairs stored in fhex[]
file_to_fhex () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local x ;fhex=()

	[[ -f "$1" ]] || { err_msg+=("\"$1\" not found") ;return 1 ; }

	exec 5<"$1" || return $?
	while IFS= read -r -d $'\0' -n 1 -u 5 x ;do
		printf -v x '%02x' "'$x"
		fhex+=($x)
		((${#fhex[*]}>MAX_FILE_SIZE)) && { err_msg+=("\"$1\" exceeds ${MAX_FILE_SIZE} bytes") ; break ; }
	done
	exec 5<&-

	((${#err_msg[*]})) && return 1
	vecho 1 "$z: bytes read: ${#fhex[*]}"
}

# progress indicator
# progressbar part whole [units]
#   progressbar 14 120
#   [####====================================] 11%
#   progressbar 14 120 seconds
#   [####====================================] 11% (14/120 seconds)
progressbar () {
	((v)) && return
	local -i i p=$1 w=$2 p_len w_len=40 ;local b= s= u=$3
	local -i c=$((p*100/w))
	p_len=$((p*w_len/w))
	for ((i=0;i<w_len;i++)) { ((i<p_len)) && b+='#' || b+='=' ; }
	printf '\r%79s\r[%s] %d%%%s' '' "$b" "$c" "${u:+ ($p/$w $u)}"
}

# busy indicator
# Looping animation for when you don't know how long something will take.
# The animation "frames" are defined in the array anim[]. When called, it just
# backspaces the length of a frame, and prints the next frame.
spin () {
	((v)) && return
	printf '%b%s' "${anim[0]//?/\\b}" "${anim[y]}"
	((++y>=${#anim[*]})) && y=0
}

###############################################################################
# Main Command Dispatcher

do_cmd () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i i e= ;local s="$@" a=() c ifs=$IFS IFS=';' ;a=($s) IFS=$ifs
	for ((i=0;i<${#a[*]};i++)) {
		set ${a[i]}
		c=$1 ;shift
		err_msg=()
		case $c in

	# operation-mode commands
	# All of the drive firmware "operation mode" functions.
	# Most of these are low-level, not used directly by a user.
	# Higher-level commands like ls, load, & save are built out of these.
			dirent) ocmd_dirent ;e=$? ;;
			open) ocmd_open $* ;e=$? ;;
			close) ocmd_close ;e=$? ;;
			read) ocmd_read $* ;e=$? ;;
			write) ocmd_write $* ;e=$? ;;
			delete) ocmd_delete ;e=$? ;;
			format) ocmd_format ;e=$? ;;
			status) ocmd_status ;e=$? ;((e)) || echo "OK" ;;
			fdc) ocmd_fdc ;e=$? ;;

	# fdc-mode commands
	# All of the drive firmware "FDC mode" functions.
			${fdc_cmd[mode]}|mode) fcmd_mode $* ;e=$? ;; # select operation-mode or fdc-mode
			${fdc_cmd[condition]}|condition) fcmd_condition $* ;e=$? ;; # get drive condition
# name conflict 	#${fdc_cmd[format]}|format) fcmd_format $* ;e=$? ;; # format disk
			#${fdc_cmd[formatnv]}|formatnv) fcmd_formatnv $* ;e=$? ;; # format disk no verify
			#${fdc_cmd[readid]}|readid) fcmd_readid $* ;e=$? ;; # read id
			#${fdc_cmd[readsect]}|readsect) fcmd_readsect $* ;e=$? ;; # read sector
			#${fdc_cmd[searchid]}|searchid) fcmd_searchid $* ;e=$? ;; # search id
			#${fdc_cmd[writeid]}|writeid) fcmd_writeid $* ;e=$? ;; # write id
			#${fdc_cmd[writeidnv]}|writeidnv) fcmd_writeidnv $* ;e=$? ;; # write id no verify
			#${fdc_cmd[writesect]}|writesect) fcmd_writesect $* ;e=$? ;; # write sector
			#${fdc_cmd[writesectnv]}|writesectnv) fcmd_writesectnv $* ;e=$? ;; # write sector no verify

	# local/client commands
			ls|dir) lcmd_ls "$@" ;e=$? ;;
			rm|del) lcmd_rm "$@" ;e=$? ;;
			load) lcmd_load "$@" ;e=$? ;;
			save) lcmd_save "$@" ;e=$? ;;
			mv|ren) lcmd_mv "$@" ;e=$? ;;
			cp|copy) lcmd_cp "$@" ;e=$? ;;
			sync|drain) tpdd_iosync ;e=$? ;;
			q|quit|bye|exit) exit ;;

	# low level manual raw/debug commands
			com_test) lcmd_com_test ;e=$? ;; # check if port open
			com_open) lcmd_com_open ;e=$? ;; # open the port
			com_close) lcmd_com_close ;e=$? ;; # close the port
			com_read) lcmd_com_read $* ;e=$? ;; # read $1 bytes
			com_write) lcmd_com_write $* ;e=$? ;; # write $* (hex pairs)
			com_ret) lcmd_com_ret ;e=$? ;; # read a return packet
			com_req) lcmd_com_req $* ;e=$? ;; # write a request packet
			sum) calc_cksum $* ;e=$? ;;

	# playground
			# send the TPDD1 bootstrap S-records
			tpdd1_boot) lcmd_tpdd1_boot ;e=$? ;;
			anim|play) lcmd_play_anim $* ;e=$? ;;

			'') : ;;
			*) echo "Unknown command: \"$c\"" >&2 ;;
		esac
		((${#err_msg[*]})) && printf '\n%s: %s\n' "$c" "${err_msg[@]}" >&2
	}
	return $e
}

###############################################################################
# experimental junk

lcmd_tpdd1_boot () {
	local x=
	str_to_hex "S10985157C00AD7EF08B3AS901FE"
	tpdd_write ${hex[*]} 0d
	while tpdd_read 1 ;do x+=" ${rhex[*]}" ;done
	printf '%b' "\x${x// /\\x}"
}

###############################################################################
# serial port operations

get_tpdd_port () {
	local x=(/dev/${TPDD_TTY_PREFIX#/dev/}*)
	[[ "${x[0]}" == "/dev/${TPDD_TTY_PREFIX}*" ]] && x=(/dev/tty*)
	((${#x[*]}==1)) && { PORT=${x[0]} ;return ; }
	local PS3="Which serial port is the TPDD drive on? "
	select PORT in ${x[*]} ;do [[ -c "$PORT" ]] && break ;done
}

test_com () {
	{ : >&3 ; } 2>&-
}

open_com () {
	test_com && return
	exec 3<>"${PORT}"
	stty ${stty_f} "${PORT}" ${STTY_FLAGS}
	test_com || abrt "Failed to open serial port \"${PORT}\""
}

close_com () {
	exec 3>&-
}

###############################################################################
# TPDD communication primitives

# write $* to com port as binary
tpdd_write () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local x=$*
	((v>2)) && { local c=$((10000+seq++)) ;printf '%b' "\x${x// /\\x}" >${0##*/}.$$.${c#?}.$z ; }
	printf '%b' "\x${x// /\\x}" >&3
}

# read $1 bytes from com port
# store each byte as a hex pair in global rhex[]
# deep brute force magic here to actually read null bytes
# (we're not actually reading or storing nulls, but we are *detecting* them and recording where they were)
# Thanks to Andrew Ayers in the M100 group on Facebook for help finding the key trick.
#
# return value from "read" is crucial to distiguish a timeout from a null byte
# $?=0 = we read a non-null byte normally, $x contains a byte
#    1 = we read a null byte, $x is empty because we ate the null as a delimiter
# >128 = we timed out, $x is empty because there was no data, not even a null
tpdd_read () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i i l=$1 ;local x ;rhex=() read_err=0
	tpdd_wait || return $?
	vecho 1 -n "$z: l=$l "
	for ((i=0;i<l;i++)) {
		vecho 1 -n " $i:"
		x= rhex[i]='00'
		((read_err)) && { vecho 1 -n "XX" ; continue ; }
		IFS= read -t $read_timeout -r -d $'\0' -n 1 -u 3 x ;read_err=$?
		((read_err>1)) || read_err=0
		printf -v rhex[i] '%02x' "'$x"
		vecho 1 -n "${rhex[i]}"
	}
	((v>2)) && { local c=$((10000+seq++)) ;x="${rhex[*]}" ;printf '%b' "\x${x// /\\x}" >${0##*/}.$$.${c#?}.$z ; }
	((read_err>1)) && vecho 1 " read_err:$read_err" || vecho 1 ''
}

# check if data is available without consuming any
tpdd_check () {
	IFS= read -t 0 -u 3
}

# wait for data
# tpdd_wait timeout_ms busy_indication
tpdd_wait () {
	local z=${FUNCNAME[0]} ;vecho 1 -n "$z($@):"
	local d=(: spin progressbar)
	local -i i=-1 n t=${1:-$TPDD_WAIT_TIMEOUT_MS} b=$2
	((t<TTY_READ_TIMEOUT_MS)) && t=$TTY_READ_TIMEOUT_MS
	n=$((t/TTY_READ_TIMEOUT_MS))
	((b==1)) && printf '%s' "${anim[0]//?/ }"
	until ((++i>n)) ;do
		tpdd_check && break
		${d[b]} $i $n
		_sleep $read_timeout
	done
	((i>n)) && { err_msg+=('TIMED OUT') ;return 1 ; }
	${d[b]} 1 1
	((b==1)) && printf '%b%s%b' "${anim[0]//?/\\b}" "${anim[0]//?/ }" "${anim[0]//?/\\b}"
	vecho 1 "$i"
}

# Drain any pending output from the drive.
# Read and discard bytes one at a time until hitting a read timeout.
tpdd_iosync () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	while tpdd_check ;do tpdd_read 1 ;done
	rhex=()
}

###############################################################################
#                             OPERATION MODE                                  #
###############################################################################
#
# operation-mode transaction format reference
#
# request block
#
#   preamble  2 bytes       5A5A
#   format    1 byte        type of request block
#   length    1 byte        length of data in bytes
#   data      0-128 bytes   data
#   checksum  1 byte        1's comp of LSByte of sum of format through data
#
# return block
#
#   format    1 byte        type of return block
#   length    1 byte        length of data in bytes
#   data      0-128 bytes   data
#   checksum  1 byte        1's comp of LSByte of sum of format through data



###############################################################################
# "Operation Mode" support functions

# calculate the checksum of $* (hex pairs)
# return in global $cksum (hex pair)
calc_cksum () {
	local z=${FUNCNAME[0]} ;vecho 1 -n "$z($@):"
	local -i s=0
	while (($#)) ;do ((s+=16#$1)) ;shift ;done
	s=$(((s&255)^255))
	printf -v cksum '%02x' $s
	vecho 1 "$cksum"
}

# verify the checksum of a received packet
# $* = data data data... csum  (hex pairs)
verify_checksum () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i l=$(($#-1)) ;local x= h=($*)
	x=${h[l]} ;h[l]=
	calc_cksum ${h[*]}
	vecho 1 "$z: received: \"$x\""
	vecho 1 "$z: computed: \"$cksum\""
	[[ "$x" == "$cksum" ]]
}

# check if a ret_std format response was ok (00) or error
ocmd_check_err () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i e ;local x
	vecho 1 "$z: ret_fmt=$ret_fmt ret_len=$ret_len ret_dat=(${ret_dat[*]}) read_err=\"$read_err\""
	((${#ret_dat[*]}==1)) || { err_msg+=('Corrupt Response') ; ret_dat=() ;return 1 ; }
	vecho 1 -n "$z: ${ret_dat[0]}:"
	e=$((16#${ret_dat[0]}))
	x='OK'
	((e)) && {
		x='UNKNOWN ERROR'
		((${#opr_msg[${ret_dat[0]}]})) && x="${opr_msg[${ret_dat[0]}]}"
		err_msg+=("$x")
	}
	vecho 1 "$x"
	return $e
}

# build a valid operation-mode request block and send it to the tpdd
# 5a 5a format length data checksum
# fmt=$1  data=$2-*
ocmd_send_req () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	local fmt=$1 len ;shift
	printf -v len '%02x' $#
	calc_cksum $fmt $len $*
	vecho 1 "$z: fmt=\"$fmt\" len=\"$len\" dat=\"$*\" sum=\"$cksum\""
	tpdd_write 5a 5a $fmt $len $* $cksum
}

# read an operation-mode return block from the tpdd
# parse it into the parts: format, length, data, checksum
# verify the checksum
# return the globals ret_fmt, ret_len, ret_dat[], ret_sum
ocmd_read_ret () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i t ;local l x ;ret_fmt= ret_len= ret_dat=() ret_sum=

	vecho 1 "$z: reading 2 bytes (fmt len)"
	tpdd_read 2 || return $?
	vecho 1 "$z: (${rhex[*]})"
	((${#rhex[*]}==2)) || return 1
	case "${rhex[0]}" in
		10|11|12) ret_fmt=${rhex[0]} ret_len=${rhex[1]} ;;
		*) { err_msg+=('INVALID RESPONSE') ;rhex=() ;return 1 ; } ;;
	esac

	l=$((16#${ret_len:-00}))
	vecho 1 "$z: reading 0x$ret_len($l) bytes (data)"
	tpdd_read $l || return $?
	((${#rhex[*]}==l)) || return 3
	ret_dat=(${rhex[*]})
	vecho 1 "$z: data=(${ret_dat[*]})"

	vecho 1 "$z: reading 1 byte (checksum)"
	tpdd_read 1 || return $?
	((${#rhex[*]}==1)) || return 4
	ret_sum=${rhex[0]}
	vecho 1 "$z: cksum=$ret_sum"

	# compute the checksum and verify it matches the supplied checksum
	verify_checksum $ret_fmt $ret_len ${ret_dat[*]} $ret_sum || { err_msg+=('CHECKSUM FAILED') ; return 5 ; }
}

# Space-pad or truncate $1 to 24 bytes.
# If in "Floppy Compatible" mode, and if the filename is already 6.2 or less,
# then also space-pad to %-6s.%-2s within that. Return in global tpdd_file_name
# normal       : "hi.bat"                -> "hi.bat                  "
# floppy_compat: "A.CO"   -> "A     .CO" -> "A     .CO               "
# floppy_compat: "Floppy_SYS"            -> "Floppy_SYS              "
mk_tpdd_file_name () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i e ;local x t f="$1" ;tpdd_file_name=

	$FLOPPY_COMPAT && {
		t=${1%.*} x=${1##*.}
		((${#t})) && ((${#t}<7)) && ((${#x}<3)) && printf -v f '%-6s.%-2s' "$t" "$x"
	}

	# This always, FLOPPY_COMPAT or not.
	printf -v tpdd_file_name '%-24.24s' "$f"
}

# Un-pad a padded 6.2 on-disk filename to it's normal form.
# If in "Floppy Compatible" mode, and the filename would fit within 6.2, then
# collapse the internal spaces.
un_tpdd_file_name () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local f= x= ;file_name="$1"

	$FLOPPY_COMPAT && {
		f=${file_name// /} ;x=${f##*.} ;f=${f%.*}
		((${#f})) && ((${#f}<7)) && ((${#x}<3)) && printf -v file_name '%s.%s' "$f" "$x"
	}
	:
}

###############################################################################
# "Operation Mode" drive functions
# wrappers for each "operation mode" function of the drive firmware

# directory entry
# fmt = 00
# len = 1a
# filename = 24 bytes
# attribute = "F" (always)
# search form = 00=set_name | 01=get_first | 02=get_next
ocmd_dirent () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i e ;local x f="$1" m=${3:-${dirent_cmd[get_first]}}
	drive_err= file_name= file_attr= file_len= free_sectors=
	((operation_mode)) || fcmd_mode 1

	# construct the request
	mk_tpdd_file_name "$f"			# pad/truncate filename
	str_to_hex "$tpdd_file_name"		# filename (hex[0-23])
	printf -v hex[24] '%02x' "'${2:-F}"	# attribute - always "F"
	printf -v hex[25] '%02x' $m		# search form (set_name, get_first, get_next)

	# send the request
	ocmd_send_req ${opr_fmt[req_dirent]} ${hex[*]} || return $?

	# read the response
	ocmd_read_ret || return $?

	# check which kind of response we got
	case "$ret_fmt" in
		"${opr_fmt[ret_std]}") ocmd_check_err || return $? ;;	# got a valid error return
		"${opr_fmt[ret_dirent]}") : ;;				# got a valid dirent return
		*) err_msg+=("$z:Corrupt Return") ;return 1 ;;		# got no valid return
	esac
	((${#ret_dat[*]}==28)) || { err_msg+=("$z:Corrupt Return") ;return 1 ; }

	# parse a dirent return format
	free_sectors=$((16#${ret_dat[27]})) ;ret_dat[27]=
	file_len=$(( 16#${ret_dat[25]}*256 + 16#${ret_dat[26]} )) ;ret_dat[26]= ret_dat[25]=
	printf -v file_attr '%b' "\x${ret_dat[24]}" ;ret_dat[24]=
	x=(${ret_dat[*]}) ;x="${x[*]}" ;printf -v file_name '%-24.24b' "\x${x// /\\x}"
	vecho 1 "$z: mode=$m filename=\"$file_name\" attr=\"$file_attr\" len=$file_len free=$free_sectors"

	# If doing set_name, and we got this far, then return success. Only the
	# caller knows if they expected file_name & file_attr to be null or not.
	[[ "$m" == "${dirent_cmd[set_name]}" ]] && return 0

	# If doing get_first or get_next, filename[0]=00 means no more files.
	[[ ${ret_dat[0]} == '00' ]] && return 1 || return 0
}

# Get Drive Status
# request: 5a 5a 07 00 ##
# return : 07 01 ?? ##
ocmd_status () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	ocmd_send_req ${opr_fmt[req_status]} || return $?
	ocmd_read_ret || return $?
	ocmd_check_err || return $?
}

# Format Disk
#request: 5a 5a 06 00 ##
#return : 12 01 ?? ##
ocmd_format () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1

	echo "Formatting disk"
	ocmd_send_req ${opr_fmt[req_format]} || return $?
	tpdd_wait $FORMAT_WAIT_MS 2 || return $?
	echo

	ocmd_read_ret || return $?
	ocmd_check_err || return $?
}

# switch to FDC mode
ocmd_fdc () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	ocmd_send_req ${opr_fmt[req_fdc]} || return $?
	operation_mode=0
}

# Open File
# request: 5a 5a 01 01 MM ##
# return : 12 01 ?? ##
# MM = access mode: 01=write_new, 02=write_append, 03=read
ocmd_open () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	local m ;printf -v m '%02x' $1
	ocmd_send_req ${opr_fmt[req_open]} $m || return $?	# open the file
	ocmd_read_ret || return $?
	ocmd_check_err
}

# Close File
# request: 5a 5a 02 00 ##
# return : 12 01 ?? ##
ocmd_close () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	ocmd_send_req ${opr_fmt[req_close]} || return $?
	ocmd_read_ret || return $?
	ocmd_check_err
}

# Delete File
# request: 5a 5a 05 00 ##
# return : 12 01 ?? ##
ocmd_delete () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	ocmd_send_req ${opr_fmt[req_delete]} || return $?
	tpdd_wait $DELETE_WAIT_MS 1 || return $?
	ocmd_read_ret || return $?
	ocmd_check_err
}

# Read File data
# request: 5a 5a 03 00 ##
# return : 10 00-80 1-128bytes ##
ocmd_read () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	ocmd_send_req ${opr_fmt[req_read]} || return $?
	ocmd_read_ret || return $?
	vecho 1 "$z: ret_fmt=$ret_fmt ret_len=$ret_len ret_dat=(${ret_dat[*]}) read_err=\"$read_err\""

	# check if the response was an error
	case "$ret_fmt" in
		"${opr_fmt[ret_std]}") ocmd_check_err || return $? ;;
		"${opr_fmt[ret_read]}") ;;
		*) err_msg+=('Unexpected Response') ;return 4 ;;
	esac

	# return true or not based on data or not
	# so we can do "while ocmd_read ;do ... ;done"
	((${#ret_dat[*]}))
}

# Write File Data
# request: 5a 5a 04 ?? 1-128 bytes ##
# return : 12 01 ?? ##
ocmd_write () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) || fcmd_mode 1
	(($#)) || return 128
	ocmd_send_req ${opr_fmt[req_write]} $* || return $?
	tpdd_check || return 0		# no return block sent unless error
	ocmd_read_ret || return $?
	ocmd_check_err
}

###############################################################################
#                                 FDC MODE                                    #
###############################################################################
#
# fdc-mode transaction format reference
#
# send: C [ ] [P[,P]...] CR
#
# C = command letter, ascii letter
# optional space between command letter and first parameter
# P = parameter (if any), integer decimal value in ascii numbers
# ,p = more parameters if any, seperated by commas, ascii decimal numbers
# CR = carriage return
#
# recv: 8 bytes as 4 ascii hex pairs representing 4 byte values
#
#  1st pair is the error status
#  remaining pairs meaning depends on the command
#
# Some fdc commands have another send-and-receive after that.
# Receive the first response, if the status is not error, then:
#
# send: the data for a sector write
# recv: another standard 8-byte response as above
# or
# send: single carriage-return
# recv: data from a sector read

###############################################################################
# "FDC Mode" support functions

# read an FDC-mode 8-byte result packet
fcmd_read_result () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) && ocmd_fdc
	local -i i ;local x ;fdc_err= fdc_res= fdc_len= fdc_res_b=()

	# read 8 bytes
	tpdd_read 8

	# re-constitute the 8 hex pairs from tpdd_write(), back to the original
	# 8 ascii characters sent by the drive
	x="${rhex[*]}" ;printf -v x '%b' "\x${x// /\\x}"
	vecho 1 "$z:$x"

	# the 8 characters sent by the drive are themselves hex pairs,
	# representing integer values not ascii characters in this case
	fdc_err=$((16#${x:0:2})) # first 2 status
	fdc_res=$((16#${x:2:2})) # next 2  result
	fdc_len=$((16#${x:4:4})) # last 4  length

	# look up the error message for fdc_err if not 0
	((v)) && {
		x='OK'
		((fdc_err)) && {
			x='ERROR'
			[[ "${fdc_msg[fdc_err]}" ]] && x="${fdc_msg[fdc_err]}"
			err_msg+=("$x")
		}
		vecho 1 -n "$z:status: $fdc_err - $x"
	}

	# fdc_result is 8 individual bits
	# convert to an array for convenience
	fdc_result_b=()
	for ((i=7;i>=0;i--)) { fdc_result_b+=(${D2B[fdc_res]:i:1}) ; }

	return $fdc_err
}

###############################################################################
# "FDC Mode" drive functions
# wrappers for each "FDC mode" function of the drive firmware

# select operation mode
# $1 0=fdc 1=operation
fcmd_mode () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	(($#)) || return
	str_to_hex "${fdc_cmd[mode]}$1"
	tpdd_write ${hex[*]} 0d
	operation_mode=$1
}

fcmd_condition () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	((operation_mode)) && ocmd_fdc
	local -i ;local x
	str_to_hex "${fdc_cmd[condition]}"
	tpdd_write ${hex[*]} 0d

	fcmd_read_result
	((fdc_status)) && return $fdc_status

	# result bit 7 - disk not inserted
	x= ;((fdc_result_b[7])) && x=' Not'
	echo -n "Disk${x} Inserted"
	((fdc_result_b[7])) && { echo ;return ; }

	# result bit 5 - disk write-protected
	x='Writable' ;((fdc_result_b[5])) && x='Write-protected'
	echo ", $x"
}

###############################################################################
# Local Commands
# high level functions implemented here in the client

# list all files
lcmd_ls () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i dirent_mode=${dirent_cmd[get_first]} i= ;local f x ;ret_dat=()

	echo "------ Directory Listing ------"
	while ocmd_dirent '' '' $dirent_mode ;do
		un_tpdd_file_name "$file_name"
		printf '%-24.24b %6u\n' "$file_name" "$file_len"
		((dirent_mode==${dirent_cmd[get_first]})) && dirent_mode=${dirent_cmd[get_next]}
	done
	echo "-------------------------------"
	echo "$((free_sectors*1280)) bytes free"
}

# load a file (copy a file from tpdd to local file or memory)
# lcmd_load source_filename [destination_filename]
# If $2 is set but empty, read into global fhex[] instead of writing a file
lcmd_load () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local x s d ;local -i p= m= l= ;fhex=()
	[[ "$1" ]] || return 1
	s=$1 d=${2:-$s}
	(($#>1)) && ((${#2}==0)) && m=1 		# read into memory instead of file
	ocmd_dirent "$s" '' ${dirent_cmd[set_name]} || return $?	# set the source filename
	l=$file_len					# file size provided by dirent()
	echo -n "Loading TPDD:$s" ;((m)) && echo || echo " to $d"
	progressbar 0 $l "bytes"
	ocmd_open ${open_mode[read]} || return $?	# open the source file for reading
	((m)) || >"$d"					# start the destination file
	while ocmd_read ;do				# read a block of data from tpdd
		((m)) && {
			fhex+=(${ret_dat[*]})		# add to hex[]
		} || {
			x="${ret_dat[*]}" ;printf '%b' "\x${x// /\\x}" >> "$d"	# add to file
		}
		((p+=${#ret_dat[*]})) ;progressbar $p $l "bytes"
		((${#ret_dat[*]}<128)) && break		# stop when we get less than 128 bytes
	done
	ocmd_close || return $?				# close the source file
	((p==l)) || { err_msg+=('Error') ; return 1 ; }
	echo
}

# save a file (copy a file from local file or memory to tpdd)
# lcmd_save source_filename [destination_filename]
# If $1 is set but empty, get data from global fhex[] instead of reading a file
lcmd_save () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	local -i i n e p= l= b= ;local s d w h x
	(($#)) || return 2
	s=$1 d=${2:-$1}
	((${#d})) || return 3
	((${#1})) && { file_to_fhex "$s" || return 4 ; }
	h=(${fhex[*]})
	l=${#h[*]}				# file size
	echo "Saving TPDD:$d"
	progressbar 0 $l "bytes"

	ocmd_dirent "$d" '' ${dirent_cmd[set_name]} || return $?	# set the destination filename
	ocmd_open ${open_mode[write_new]} || return $?			# open the set file for writing
	while ((${#h[*]})) ;do
		vecho 1 "$z: packet:$((++p)) start #h=${#h[*]}"

		w=() n=${#h[*]}
		((n>128)) && n=128
		for ((i=0;i<n;i++)) { w+=(${h[i]}) h[i]= ; } ;h=(${h[*]})
		vecho 1 "$z: packet:$p end #h=${#h[*]}"

		ocmd_write ${w[*]} || return $?		# write w[] to the set file

		tpdd_wait				# read the response from write
		ocmd_read_ret || return $?
		ocmd_check_err || return $?

		progressbar $((b+=n)) $l "bytes"
	done
	ocmd_close || return $?			# close the set file
	echo
}

lcmd_rm () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	[[ "$1" ]] || return 1
	echo -n "Deleting TPDD:$1 "
	ocmd_dirent "$1" '' ${dirent_cmd[set_name]} || return $?	# set the filename
	ocmd_delete || return $?
	printf '\r%79s\rDeleted TPDD:%s\n' '' "$1"
}

# for now, mv and cp are almost the same and mostly redundant,
# but eventually mv may be totally different, based on
# fdc-mode commands to read and re-write the directory track
# instead of doing load-delete-save
#
# rm before save is less safe, but it's so that it works when the disk is full
lcmd_mv () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	(($#==2)) || return 1
	lcmd_load $1 '' && lcmd_rm $1 && lcmd_save '' $2
}

lcmd_cp () {
	local z=${FUNCNAME[0]} ;vecho 1 "$z($@)"
	(($#==2)) || return 1
	lcmd_load $1 '' && lcmd_save '' $2
}

###############################################################################
# manual/raw debug commands

lcmd_com_test () {
	test_com && echo "com is open" || echo "com is closed"
}

lcmd_com_open () {
	open_com
	lcmd_com_test
}

lcmd_com_close () {
	close_com
	lcmd_com_test
}

lcmd_com_read () {
	tpdd_read $1
	printf '%s\n' "${rhex[@]}"
}

lcmd_com_write () {
	tpdd_write $*
}

lcmd_com_ret () {
	ocmd_read_ret
	printf '%s\n' "${ret_dat[@]}"
}

lcmd_com_req () {
	ocmd_send_req $*
}

lcmd_play_anim () {
	local -i i
	echo
	for ((i=0;i<$1;i++)) { spin ;_sleep 0.1 ; }
	echo
}

###############################################################################
# Main
typeset -a err_msg=() hex=() fhex=() rhex=() ret_dat=() fdc_res_b=()
typeset -i operation_mode=1 read_err= fdc_err= fdc_res= fdc_len=
cksum=00 ret_fmt= ret_len= ret_sum= tpdd_file_name= file_name=
readonly LANG=C D2B=({0,1}{0,1}{0,1}{0,1}{0,1}{0,1}{0,1}{0,1})
((v>2)) && typeset -i seq=0
x=$((1000000+TTY_READ_TIMEOUT_MS)) ;readonly read_timeout="${x:1:-3}.${x: -3}" ;unset x
typeset -ar anim=("${SPINNER_ANIMATION_FRAMES[@]}") ;typeset -i y=

# for _sleep()
readonly sleep_fifo="/tmp/.${0//\//_}.sleep.fifo"
[[ -p $sleep_fifo ]] || mkfifo $sleep_fifo || abrt "Error creating sleep fifo \"$sleep_fifo\""
exec 4<>$sleep_fifo

# tpdd serial port
PORT="/dev/${1#/dev/}" ;[[ -c "$PORT" ]] && shift || get_tpdd_port
vecho 1 "Using port \"$PORT\""
open_com || exit $?

# non-interactive mode
(($#)) && { do_cmd "$@" ; exit ; }

# interactive mode
while read -p"TPDD(${mode[operation_mode]})>" x ;do do_cmd "$x" ;done
